[0m15:56:58.327673 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d876b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105ceb350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105ceaf30>]}


============================== 15:56:58.331052 | be55bc5e-aa7c-4150-b6ef-dada7eb38bc5 ==============================
[0m15:56:58.331052 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:56:58.331416 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/poojan/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:56:58.340793 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/poojan/.dbt')}
[0m15:56:58.341088 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:57:25.850381 [debug] [MainThread]: Starter project path: /Users/poojan/Desktop/Project/Project/env/lib/python3.12/site-packages/dbt/include/starter_project
[0m15:57:25.875142 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:57:25.875804 [info ] [MainThread]: Setting up your profile.
[0m16:01:33.947749 [info ] [MainThread]: Profile data_pipeline written to /Users/poojan/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:01:34.291713 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 276.01816, "process_in_blocks": "0", "process_kernel_time": 0.304328, "process_mem_max_rss": "102023168", "process_out_blocks": "0", "process_user_time": 0.939847}
[0m16:01:34.295464 [debug] [MainThread]: Command `dbt init` succeeded at 16:01:34.294578 after 276.03 seconds
[0m16:01:34.300673 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052ee930>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105ca1190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a716d0>]}
[0m16:01:34.303074 [debug] [MainThread]: Flushing usage events
[0m16:01:34.639968 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:02:35.679235 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106dc49e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108da7470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108da6ff0>]}


============================== 16:02:35.682327 | 42252945-f3ab-4a30-9476-63d5e1baacc8 ==============================
[0m16:02:35.682327 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:02:35.682669 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/poojan/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run --threads 10', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:02:35.683191 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/poojan/Desktop/Project/Project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:02:35.684799 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.051122874, "process_in_blocks": "0", "process_kernel_time": 0.151085, "process_mem_max_rss": "100777984", "process_out_blocks": "0", "process_user_time": 0.663806}
[0m16:02:35.685125 [debug] [MainThread]: Command `dbt run` failed at 16:02:35.685068 after 0.05 seconds
[0m16:02:35.685358 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ac79e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10896b140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108da72f0>]}
[0m16:02:35.685573 [debug] [MainThread]: Flushing usage events
[0m16:02:35.899879 [debug] [MainThread]: An error was encountered while trying to flush usage events
